services:
  - type: web
    name: todo-service
    runtime: node
    plan: free
    autoDeploy: false
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
